apiVersion: batch/v1
kind: Job
metadata:
  name: result-stress-test
  namespace: voting-app
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hey
          image: williamyeh/hey:latest
          args:
            - "-z"
            - "5m"
            - "-c"
            - "200"
            - "http://result.voting-app.svc.cluster.local/"
